### ISSUE TITLE
InvalidArgumentException: There is no extension able to load the configuration for "jms_payment_paypal"

### ISSUE THREAD

**Issue by lxg** [schmittjoh/JMSPaymentPaypalBundle#31]
I don't know if it's a bug or an issue on my part, but when I insert the jms_payment_paypal stuff into my config.yml, I get an Exception saying '"InvalidArgumentException: There is no extension able to load the configuration for "jms_payment_paypal"'.

I have installed the PaymentCore and PaymentPayPal via the deps file:

```
[JMSPaymentCoreBundle]
    git=git://github.com/schmittjoh/JMSPaymentCoreBundle.git
    target=/bundles/JMS/Payment/CoreBundle

[JMSPaymentPaypalBundle]
    git=git://github.com/schmittjoh/JMSPaymentPaypalBundle.git
    target=/bundles/JMS/Payment/PayPalBundle
```

After `php bin/vendors install` I have added the bundles to the list in AppKernel.php, right above my own bundles:

```
            new JMS\Payment\CoreBundle\JMSPaymentCoreBundle(),
            new JMS\Payment\PayPalBundle\JMSPaymentPaypalBundle(),
```

Then I have added the configuration to app/config/config.yml:

```
jms_payment_core:
    secret: *********************

jms_payment_paypal:
    username: "*********************"
    password: "*********************"
    signature: "*********************"
```

When I then load a page in the browser or run any of the console commands, I get the mentioned exception.

I do, however, not get the exception with only the jms_payment_core config.

What's also strange: When I enter garbage in `/vendor/bundles/JMS/Payment/PayPalBundle/DependencyInjection/Configuration.php`, I don't get an error message – so it seems that the file is not even loaded.
